//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServiceWCF.PlatosServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plato", Namespace="http://schemas.datacontract.org/2004/07/Platos.Dominio")]
    [System.SerializableAttribute()]
    public partial class Plato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_platoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_plato {
            get {
                return this.Id_platoField;
            }
            set {
                if ((this.Id_platoField.Equals(value) != true)) {
                    this.Id_platoField = value;
                    this.RaisePropertyChanged("Id_plato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/Platos.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlatosServ.IPlatos")]
    public interface IPlatos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/RegistrarPlato", ReplyAction="http://tempuri.org/IPlatos/RegistrarPlatoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestServiceWCF.PlatosServ.RepetidoException), Action="http://tempuri.org/IPlatos/RegistrarPlatoRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/Platos.Errores")]
        TestServiceWCF.PlatosServ.Plato RegistrarPlato(TestServiceWCF.PlatosServ.Plato platoCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/RegistrarPlato", ReplyAction="http://tempuri.org/IPlatos/RegistrarPlatoResponse")]
        System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato> RegistrarPlatoAsync(TestServiceWCF.PlatosServ.Plato platoCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/ModificarPlato", ReplyAction="http://tempuri.org/IPlatos/ModificarPlatoResponse")]
        TestServiceWCF.PlatosServ.Plato ModificarPlato(TestServiceWCF.PlatosServ.Plato platoCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/ModificarPlato", ReplyAction="http://tempuri.org/IPlatos/ModificarPlatoResponse")]
        System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato> ModificarPlatoAsync(TestServiceWCF.PlatosServ.Plato platoCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/EliminarPlato", ReplyAction="http://tempuri.org/IPlatos/EliminarPlatoResponse")]
        void EliminarPlato(int platoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/EliminarPlato", ReplyAction="http://tempuri.org/IPlatos/EliminarPlatoResponse")]
        System.Threading.Tasks.Task EliminarPlatoAsync(int platoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/ObtenerPlatobyID", ReplyAction="http://tempuri.org/IPlatos/ObtenerPlatobyIDResponse")]
        TestServiceWCF.PlatosServ.Plato ObtenerPlatobyID(int platoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/ObtenerPlatobyID", ReplyAction="http://tempuri.org/IPlatos/ObtenerPlatobyIDResponse")]
        System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato> ObtenerPlatobyIDAsync(int platoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/ObtenerPlatobyName", ReplyAction="http://tempuri.org/IPlatos/ObtenerPlatobyNameResponse")]
        TestServiceWCF.PlatosServ.Plato ObtenerPlatobyName(string platoName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/ObtenerPlatobyName", ReplyAction="http://tempuri.org/IPlatos/ObtenerPlatobyNameResponse")]
        System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato> ObtenerPlatobyNameAsync(string platoName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/ObtenerPlatos", ReplyAction="http://tempuri.org/IPlatos/ObtenerPlatosResponse")]
        TestServiceWCF.PlatosServ.Plato[] ObtenerPlatos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatos/ObtenerPlatos", ReplyAction="http://tempuri.org/IPlatos/ObtenerPlatosResponse")]
        System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato[]> ObtenerPlatosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlatosChannel : TestServiceWCF.PlatosServ.IPlatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatosClient : System.ServiceModel.ClientBase<TestServiceWCF.PlatosServ.IPlatos>, TestServiceWCF.PlatosServ.IPlatos {
        
        public PlatosClient() {
        }
        
        public PlatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestServiceWCF.PlatosServ.Plato RegistrarPlato(TestServiceWCF.PlatosServ.Plato platoCrear) {
            return base.Channel.RegistrarPlato(platoCrear);
        }
        
        public System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato> RegistrarPlatoAsync(TestServiceWCF.PlatosServ.Plato platoCrear) {
            return base.Channel.RegistrarPlatoAsync(platoCrear);
        }
        
        public TestServiceWCF.PlatosServ.Plato ModificarPlato(TestServiceWCF.PlatosServ.Plato platoCrear) {
            return base.Channel.ModificarPlato(platoCrear);
        }
        
        public System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato> ModificarPlatoAsync(TestServiceWCF.PlatosServ.Plato platoCrear) {
            return base.Channel.ModificarPlatoAsync(platoCrear);
        }
        
        public void EliminarPlato(int platoID) {
            base.Channel.EliminarPlato(platoID);
        }
        
        public System.Threading.Tasks.Task EliminarPlatoAsync(int platoID) {
            return base.Channel.EliminarPlatoAsync(platoID);
        }
        
        public TestServiceWCF.PlatosServ.Plato ObtenerPlatobyID(int platoID) {
            return base.Channel.ObtenerPlatobyID(platoID);
        }
        
        public System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato> ObtenerPlatobyIDAsync(int platoID) {
            return base.Channel.ObtenerPlatobyIDAsync(platoID);
        }
        
        public TestServiceWCF.PlatosServ.Plato ObtenerPlatobyName(string platoName) {
            return base.Channel.ObtenerPlatobyName(platoName);
        }
        
        public System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato> ObtenerPlatobyNameAsync(string platoName) {
            return base.Channel.ObtenerPlatobyNameAsync(platoName);
        }
        
        public TestServiceWCF.PlatosServ.Plato[] ObtenerPlatos() {
            return base.Channel.ObtenerPlatos();
        }
        
        public System.Threading.Tasks.Task<TestServiceWCF.PlatosServ.Plato[]> ObtenerPlatosAsync() {
            return base.Channel.ObtenerPlatosAsync();
        }
    }
}
